"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Brain, Lightbulb } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface CourseTabsProps {
  currentLesson: any;
  courseTitle: string;
}

export function CourseTabs({ currentLesson, courseTitle }: CourseTabsProps) {
  return (
    <Tabs defaultValue="content" className="w-full">
      <TabsList className="grid w-full grid-cols-4">
        <TabsTrigger value="content">Content</TabsTrigger>
        <TabsTrigger value="resources">Resources</TabsTrigger>
        <TabsTrigger value="transcript">Transcript</TabsTrigger>
        <TabsTrigger value="ai-quiz">AI Quiz</TabsTrigger>
      </TabsList>

      <TabsContent value="content" className="p-4 border rounded-md mt-4">
        <div className="prose max-w-none">
          <h3>Lesson Overview</h3>
          {currentLesson?.description ? (
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {currentLesson.description}
            </ReactMarkdown>
          ) : (
            <p>No description available.</p>
          )}
          <h4>Learning Objectives</h4>
          <ul>
            <li>Understand the fundamental principles of {courseTitle}</li>
            <li>Apply theoretical knowledge to practical scenarios</li>
            <li>Develop problem-solving skills through guided exercises</li>
          </ul>
        </div>
      </TabsContent>

      <TabsContent value="resources" className="p-4 border rounded-md mt-4">
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">Supplementary Materials</h3>
          <p className="text-muted-foreground">
            No resources available for this lesson.
          </p>
        </div>
      </TabsContent>

      <TabsContent value="transcript" className="p-4 border rounded-md mt-4">
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">Video Transcript</h3>
          <p className="text-muted-foreground">
            Transcript not available for this lesson.
          </p>
        </div>
      </TabsContent>

      <TabsContent value="ai-quiz" className="p-4 border rounded-md mt-4">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold">AI-Generated Quiz</h3>
            <Button>
              <Brain className="h-4 w-4 mr-2" />
              Generate New Quiz
            </Button>
          </div>
          <div className="p-4 bg-primary/5 rounded-lg">
            <div className="flex items-center gap-3 mb-4">
              <Lightbulb className="h-5 w-5 text-primary" />
              <p className="text-sm">
                This quiz is generated by AI based on the content of this
                lesson.
              </p>
            </div>
          </div>
          <div className="space-y-6">
            <div className="p-4 border rounded-lg">
              <p className="font-medium mb-3">
                1. What is the primary focus of this lesson?
              </p>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <input type="radio" id="q1-a" name="q1" />
                  <label htmlFor="q1-a">
                    Understanding theoretical concepts only
                  </label>
                </div>
                <div className="flex items-center gap-2">
                  <input type="radio" id="q1-b" name="q1" />
                  <label htmlFor="q1-b">
                    Practical application of core principles
                  </label>
                </div>
              </div>
            </div>
            <Button className="w-full">Submit Answers</Button>
          </div>
        </div>
      </TabsContent>
    </Tabs>
  );
}
