const { PrismaClient } = require("@prisma/client");
const { v4: uuidv4 } = require("uuid");

const prisma = new PrismaClient();

async function main() {
  // Create or update categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: "web-development" },
      update: {},
      create: {
        id: "cat_webdev",
        name: "Web Development",
        slug: "web-development",
        description: "Learn to build modern web applications.",
        icon: "/icons/web-dev.svg",
        image: "/images/web-dev.jpg",
        featured: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: "data-science" },
      update: {},
      create: {
        id: "cat_datasci",
        name: "Data Science",
        slug: "data-science",
        description: "Master data analysis and AI.",
        icon: "/icons/data-science.svg",
        image: "/images/data-science.jpg",
        featured: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: "business" },
      update: {},
      create: {
        id: "cat_business",
        name: "Business",
        slug: "business",
        description: "Develop business skills.",
        icon: "/icons/business.svg",
        image: "/images/business.jpg",
        featured: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: "design" },
      update: {},
      create: {
        id: "cat_design",
        name: "Design",
        slug: "design",
        description: "Create stunning designs.",
        icon: "/icons/design.svg",
        image: "/images/design.jpg",
        featured: true,
      },
    }),
  ]);

  const webDevCategory = categories.find((c) => c.slug === "web-development");
  const dataScienceCategory = categories.find((c) => c.slug === "data-science");
  const businessCategory = categories.find((c) => c.slug === "business");
  const designCategory = categories.find((c) => c.slug === "design");

  // Create or update the instructor (Diwan Malla)
  const instructor = await prisma.user.upsert({
    where: { email: "malladipin@gmail.com" },
    update: {},
    create: {
      id: "user_2w5f0X2RjqeXtuIohkCnbJiScPk",
      clerkId: "user_2w5f0X2RjqeXtuIohkCnbJiScPk",
      name: "Diwan Malla",
      email: "malladipin@gmail.com",
      role: "INSTRUCTOR",
      instructorProfile: {
        create: {
          id: uuidv4(),
          title: "Senior Educator",
          specialization: "E-Learning and Technology",
          biography:
            "Diwan Malla is a passionate educator with 15 years of experience in online learning, specializing in technology and course development.",
          website: "https://diwanmalla.com",
          socialLinks: {
            twitter: "https://twitter.com/diwanmalla",
            linkedin: "https://linkedin.com/in/diwanmalla",
          },
          featured: true,
          totalStudents: 15000,
          totalCourses: 15,
          totalReviews: 500,
          averageRating: 4.7,
          totalRevenue: 25000.0,
        },
      },
    },
  });

  // Create 15 courses
  await prisma.course.createMany({
    data: [
      // Web Development Courses (4)
      {
        id: "course_1",
        title: "Full-Stack Web Development Bootcamp",
        slug: "full-stack-web-development-bootcamp",
        description:
          "Become a full-stack developer by learning HTML, CSS, JavaScript, React, Node.js, and MongoDB.",
        shortDescription: "Master full-stack web development from scratch.",
        price: 199.99,
        discountPrice: 149.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        previewVideo: "/videos/full-stack-preview.mp4",
        level: "ALL_LEVELS",
        status: "PUBLISHED",
        featured: true,
        bestseller: true,
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English", "Spanish", "French"],
        certificateAvailable: true,
        duration: 4200, // 70 hours
        totalLessons: 150,
        totalModules: 15,
        requirements: [
          "Basic computer skills",
          "No prior coding experience required",
        ],
        learningObjectives: [
          "Build responsive websites",
          "Develop backend APIs",
          "Deploy full-stack applications",
        ],
        targetAudience: [
          "Beginners",
          "Aspiring developers",
          "Career switchers",
        ],
        tags: ["web development", "full-stack", "react", "nodejs", "mongodb"],
        rating: 4.9,
        totalStudents: 20000,
        topCompanies: ["Google", "Amazon", "Microsoft"],
        instructorId: instructor.id,
        categoryId: webDevCategory.id,
      },
      {
        id: "course_2",
        title: "Advanced React with TypeScript",
        slug: "advanced-react-typescript",
        description:
          "Learn to build scalable, type-safe web applications using React and TypeScript.",
        shortDescription: "Master React and TypeScript for modern web apps.",
        price: 129.99,
        discountPrice: 99.99,
        thumbnail:
          "https://images.unsplash.com/photo-1537432372469-4e4a2b0466d2",
        level: "INTERMEDIATE",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 1800, // 30 hours
        totalLessons: 60,
        totalModules: 8,
        requirements: ["Basic JavaScript and React knowledge"],
        learningObjectives: [
          "Build type-safe components",
          "Integrate APIs",
          "Optimize performance",
        ],
        targetAudience: ["React developers", "Frontend engineers"],
        tags: ["react", "typescript", "web development"],
        rating: 4.7,
        totalStudents: 9000,
        topCompanies: ["Facebook", "Airbnb"],
        instructorId: instructor.id,
        categoryId: webDevCategory.id,
      },
      {
        id: "course_3",
        title: "Mastering CSS Grid and Flexbox",
        slug: "mastering-css-grid-flexbox",
        description:
          "Learn modern CSS layout techniques with Grid and Flexbox for responsive designs.",
        shortDescription:
          "Create responsive layouts with CSS Grid and Flexbox.",
        price: 79.99,
        discountPrice: 59.99,
        thumbnail:
          "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8",
        level: "BEGINNER",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English", "German"],
        certificateAvailable: true,
        duration: 900, // 15 hours
        totalLessons: 30,
        totalModules: 5,
        requirements: ["Basic HTML and CSS knowledge"],
        learningObjectives: [
          "Design responsive layouts",
          "Use CSS Grid",
          "Apply Flexbox techniques",
        ],
        targetAudience: ["Web designers", "Frontend beginners"],
        tags: ["css", "grid", "flexbox", "web development"],
        rating: 4.6,
        totalStudents: 6000,
        topCompanies: [],
        instructorId: instructor.id,
        categoryId: webDevCategory.id,
      },
      {
        id: "course_4",
        title: "RESTful API Development with Node.js",
        slug: "restful-api-nodejs",
        description:
          "Build secure and scalable RESTful APIs using Node.js, Express, and PostgreSQL.",
        shortDescription: "Learn to develop RESTful APIs with Node.js.",
        price: 139.99,
        discountPrice: 109.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321497487-e288fb19713f",
        level: "ADVANCED",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 2100, // 35 hours
        totalLessons: 70,
        totalModules: 9,
        requirements: ["Intermediate JavaScript", "Basic database knowledge"],
        learningObjectives: [
          "Design RESTful APIs",
          "Secure endpoints",
          "Integrate databases",
        ],
        targetAudience: ["Backend developers", "Full-stack engineers"],
        tags: ["nodejs", "express", "postgresql", "web development"],
        rating: 4.8,
        totalStudents: 8000,
        topCompanies: ["Netflix", "Uber"],
        instructorId: instructor.id,
        categoryId: webDevCategory.id,
      },

      // Data Science Courses (4)
      {
        id: "course_5",
        title: "Data Science with Python",
        slug: "data-science-python",
        description:
          "Master data analysis, visualization, and machine learning with Python, Pandas, and Scikit-learn.",
        shortDescription: "Comprehensive data science course with Python.",
        price: 179.99,
        discountPrice: 129.99,
        thumbnail: "https://images.unsplash.com/photo-1551288049-b1f3a0c3f8e7",
        level: "BEGINNER",
        status: "PUBLISHED",
        featured: true,
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English", "Spanish"],
        certificateAvailable: true,
        duration: 3600, // 60 hours
        totalLessons: 120,
        totalModules: 12,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Analyze data with Pandas",
          "Visualize with Seaborn",
          "Build ML models",
        ],
        targetAudience: ["Beginners", "Data enthusiasts"],
        tags: ["python", "data science", "pandas", "machine learning"],
        rating: 4.9,
        totalStudents: 15000,
        topCompanies: ["IBM", "Google"],
        instructorId: instructor.id,
        categoryId: dataScienceCategory.id,
      },
      {
        id: "course_6",
        title: "Machine Learning with R",
        slug: "machine-learning-r",
        description:
          "Learn machine learning techniques and statistical modeling using R.",
        shortDescription: "Master machine learning with R programming.",
        price: 149.99,
        discountPrice: 119.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        level: "INTERMEDIATE",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 2400, // 40 hours
        totalLessons: 80,
        totalModules: 10,
        requirements: ["Basic R knowledge", "Statistics fundamentals"],
        learningObjectives: [
          "Apply ML algorithms",
          "Perform statistical analysis",
          "Visualize data",
        ],
        targetAudience: ["Data scientists", "Analysts"],
        tags: ["r", "machine learning", "data science"],
        rating: 4.7,
        totalStudents: 7000,
        topCompanies: ["Pfizer", "Merck"],
        instructorId: instructor.id,
        categoryId: dataScienceCategory.id,
      },
      {
        id: "course_7",
        title: "Big Data with Apache Spark",
        slug: "big-data-apache-spark",
        description:
          "Learn to process and analyze large datasets using Apache Spark and PySpark.",
        shortDescription: "Master big data processing with Apache Spark.",
        price: 169.99,
        discountPrice: 139.99,
        thumbnail:
          "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5",
        level: "ADVANCED",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 2700, // 45 hours
        totalLessons: 90,
        totalModules: 10,
        requirements: ["Intermediate Python", "Data processing basics"],
        learningObjectives: [
          "Process big data",
          "Use PySpark",
          "Optimize data pipelines",
        ],
        targetAudience: ["Data engineers", "Big data professionals"],
        tags: ["spark", "pyspark", "big data", "data science"],
        rating: 4.8,
        totalStudents: 6000,
        topCompanies: ["Databricks", "Amazon"],
        instructorId: instructor.id,
        categoryId: dataScienceCategory.id,
      },
      {
        id: "course_8",
        title: "SQL for Data Science",
        slug: "sql-data-science",
        description:
          "Learn SQL to query and analyze large datasets for data science projects.",
        shortDescription: "Master SQL for data science applications.",
        price: 89.99,
        discountPrice: 69.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        level: "BEGINNER",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English", "French"],
        certificateAvailable: true,
        duration: 1200, // 20 hours
        totalLessons: 40,
        totalModules: 6,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Write SQL queries",
          "Analyze datasets",
          "Joinculus",
        ],
        targetAudience: ["Beginners", "Data analysts"],
        tags: ["sql", "data science", "database"],
        rating: 4.6,
        totalStudents: 10000,
        topCompanies: [],
        instructorId: instructor.id,
        categoryId: dataScienceCategory.id,
      },

      // Business Courses (3)
      {
        id: "course_9",
        title: "Digital Marketing Strategy",
        slug: "digital-marketing-strategy",
        description:
          "Learn SEO, content marketing, social media, and analytics to grow your business.",
        shortDescription: "Master digital marketing for business growth.",
        price: 159.99,
        discountPrice: 109.99,
        thumbnail: "https://images.unsplash.com/photo-1557838923-2985c318be48",
        level: "ALL_LEVELS",
        status: "PUBLISHED",
        featured: true,
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English", "Spanish"],
        certificateAvailable: true,
        duration: 2400, // 40 hours
        totalLessons: 80,
        totalModules: 10,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Create marketing campaigns",
          "Optimize SEO",
          "Analyze performance",
        ],
        targetAudience: ["Marketers", "Entrepreneurs"],
        tags: ["digital marketing", "seo", "social media", "business"],
        rating: 4.8,
        totalStudents: 12000,
        topCompanies: ["HubSpot", "Google"],
        instructorId: instructor.id,
        categoryId: businessCategory.id,
      },
      {
        id: "course_10",
        title: "Agile Project Management",
        slug: "agile-project-management",
        description:
          "Learn Agile methodologies, Scrum, and Kanban for effective project management.",
        shortDescription: "Master Agile and Scrum for project success.",
        price: 129.99,
        discountPrice: 99.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        level: "INTERMEDIATE",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 1800, // 30 hours
        totalLessons: 60,
        totalModules: 8,
        requirements: ["Basic project management knowledge"],
        learningObjectives: [
          "Implement Scrum",
          "Use Kanban boards",
          "Lead Agile teams",
        ],
        targetAudience: ["Project managers", "Team leads"],
        tags: ["agile", "scrum", "project management", "business"],
        rating: 4.7,
        totalStudents: 5000,
        topCompanies: ["Atlassian", "Spotify"],
        instructorId: instructor.id,
        categoryId: businessCategory.id,
      },
      {
        id: "course_11",
        title: "Business Analytics Fundamentals",
        slug: "business-analytics-fundamentals",
        description:
          "Learn to analyze business data and make data-driven decisions using Excel and Tableau.",
        shortDescription: "Master business analytics with Excel and Tableau.",
        price: 99.99,
        discountPrice: 79.99,
        thumbnail:
          "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
        level: "BEGINNER",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 1500, // 25 hours
        totalLessons: 50,
        totalModules: 7,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Analyze business data",
          "Create dashboards",
          "Make data-driven decisions",
        ],
        targetAudience: ["Business analysts", "Managers"],
        tags: ["business analytics", "excel", "tableau", "business"],
        rating: 4.6,
        totalStudents: 4000,
        topCompanies: [],
        instructorId: instructor.id,
        categoryId: businessCategory.id,
      },

      // Design Courses (4)
      {
        id: "course_12",
        title: "UI/UX Design Bootcamp",
        slug: "ui-ux-design-bootcamp",
        description:
          "Learn user interface and experience design using Figma, Adobe XD, and user testing.",
        shortDescription: "Become a UI/UX designer with hands-on projects.",
        price: 169.99,
        discountPrice: 119.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321497487-e288fb19713f",
        level: "ALL_LEVELS",
        status: "PUBLISHED",
        featured: true,
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English", "Spanish"],
        certificateAvailable: true,
        duration: 3000, // 50 hours
        totalLessons: 100,
        totalModules: 12,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Design user interfaces",
          "Conduct user research",
          "Create prototypes",
        ],
        targetAudience: ["Beginners", "Aspiring designers"],
        tags: ["ui design", "ux design", "figma", "design"],
        rating: 4.9,
        totalStudents: 11000,
        topCompanies: ["Adobe", "Airbnb"],
        instructorId: instructor.id,
        categoryId: designCategory.id,
      },
      {
        id: "course_13",
        title: "Graphic Design with Adobe Creative Suite",
        slug: "graphic-design-adobe",
        description:
          "Master Photoshop, Illustrator, and InDesign for professional graphic design.",
        shortDescription: "Learn graphic design with Adobe tools.",
        price: 139.99,
        discountPrice: 109.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        level: "BEGINNER",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 2100, // 35 hours
        totalLessons: 70,
        totalModules: 9,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Create logos",
          "Design marketing materials",
          "Edit images",
        ],
        targetAudience: ["Beginners", "Graphic designers"],
        tags: ["graphic design", "photoshop", "illustrator", "design"],
        rating: 4.8,
        totalStudents: 9000,
        topCompanies: [],
        instructorId: instructor.id,
        categoryId: designCategory.id,
      },
      {
        id: "course_14",
        title: "Motion Design with After Effects",
        slug: "motion-design-after-effects",
        description:
          "Create engaging animations and motion graphics using Adobe After Effects.",
        shortDescription: "Master motion design with After Effects.",
        price: 109.99,
        discountPrice: 89.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321497487-e288fb19713f",
        level: "INTERMEDIATE",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 1500, // 25 hours
        totalLessons: 50,
        totalModules: 7,
        requirements: ["Basic design knowledge"],
        learningObjectives: [
          "Create animations",
          "Design motion graphics",
          "Export videos",
        ],
        targetAudience: ["Designers", "Animators"],
        tags: ["motion design", "after effects", "animation", "design"],
        rating: 4.7,
        totalStudents: 6000,
        topCompanies: ["Vimeo", "Adobe"],
        instructorId: instructor.id,
        categoryId: designCategory.id,
      },
      {
        id: "course_15",
        title: "3D Design with Blender",
        slug: "3d-design-blender",
        description:
          "Learn 3D modeling, texturing, and animation using Blender for games and films.",
        shortDescription: "Master 3D design with Blender.",
        price: 119.99,
        discountPrice: 99.99,
        thumbnail:
          "https://images.unsplash.com/photo-1516321497487-e288fb19713f",
        level: "BEGINNER",
        status: "PUBLISHED",
        published: true,
        publishedAt: new Date(),
        language: "English",
        subtitlesLanguages: ["English"],
        certificateAvailable: true,
        duration: 1800, // 30 hours
        totalLessons: 60,
        totalModules: 8,
        requirements: ["No prior experience needed"],
        learningObjectives: [
          "Create 3D models",
          "Apply textures",
          "Animate objects",
        ],
        targetAudience: ["Beginners", "3D artists"],
        tags: ["3d design", "blender", "animation", "design"],
        rating: 4.8,
        totalStudents: 7000,
        topCompanies: [],
        instructorId: instructor.id,
        categoryId: designCategory.id,
      },
    ],
  });

  console.log("Seed data created successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
